version: '2'

services:
  rails:
    container_name: rails
    build: ./rails
    volumes:
    - ./railsApp:/var/www
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./server:/var/www
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php